In [189]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [190]:
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [191]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [192]:
df["size"].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [193]:
X=df[['tip','size','day','time','sex','smoker']]
y=df['total_bill']
X,y

(      tip  size   day    time     sex smoker
 0    1.01     2   Sun  Dinner  Female     No
 1    1.66     3   Sun  Dinner    Male     No
 2    3.50     3   Sun  Dinner    Male     No
 3    3.31     2   Sun  Dinner    Male     No
 4    3.61     4   Sun  Dinner  Female     No
 ..    ...   ...   ...     ...     ...    ...
 239  5.92     3   Sat  Dinner    Male     No
 240  2.00     2   Sat  Dinner  Female    Yes
 241  2.00     2   Sat  Dinner    Male    Yes
 242  1.75     2   Sat  Dinner    Male     No
 243  3.00     2  Thur  Dinner  Female     No

 [244 rows x 6 columns],
 0      16.99
 1      10.34
 2      21.01
 3      23.68
 4      24.59
        ...
 239    29.03
 240    27.18
 241    22.67
 242    17.82
 243    18.78
 Name: total_bill, Length: 244, dtype: float64)

In [194]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [195]:
import numpy
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import sys

LE1=LabelEncoder()
LE2=LabelEncoder()
LE3=LabelEncoder()
OEH=OneHotEncoder(drop='first')
ct=ColumnTransformer([('onehot',OEH,[2])],remainder='passthrough')

# Encoding categorical variables
X_train['smoker']=LE1.fit_transform(X_train['smoker'])
X_train['time']=LE2.fit_transform(X_train['time'])
X_train['sex']=LE3.fit_transform(X_train['sex'])

# Encoding categorical variables
X_test['smoker']=LE1.transform(X_test['smoker'])
X_test['time']=LE2.transform(X_test['time'])
X_test['sex']=LE3.transform(X_test['sex'])

# Applying OneHotEncoder
numpy.set_printoptions(threshold=sys.maxsize)
X_train=ct.fit_transform(X_train)
X_test=ct.transform(X_test)

In [196]:
from sklearn import svm
model = svm.SVR()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [197]:
mse,r2

(38.13576730557747, 0.5502250005312896)

In [198]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'C': [0.1, 1, 10, 100],
    'gamma': ['scale', 'auto']
}
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5)
grid_search.fit(X_train, y_train)
y_pred_1 = grid_search.predict(X_test)

In [199]:
grid_search.best_params_

{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}

In [200]:
mse = mean_squared_error(y_test, y_pred_1)
r2 = r2_score(y_test, y_pred_1)
mse ,r2

(28.78397680702266, 0.6605204492321162)